name: TechTrek Build

on:
    push:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:

        - name: Checkout source
          uses: actions/checkout@v4
  
        - name: Setup .NET 8.0
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore **\*.sln

        - name: Build solution
          run: dotnet build --no-restore --configuration Release

        - name: Run tests
          run: dotnet test --no-restore --no-build --verbosity normal
        