name: TechTrek Build

on:
    push:
        branches: [ main ]


jobs:
    build:

        runs-on: ubuntu-latest

        steps:

        - name: Checkout source
          uses: actions/checkout@v4

        - name: Print workspace path
          run: | 
              echo "Workspace directory: $GITHUB_WORKSPACE"

        - name: List files and directories
          run: |
            echo "Listing files and directories in the workspace:"
            ls -alh "${GITHUB_WORKSPACE}/src"
  
        - name: Setup .NET 8.0
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore src/Nabs.TechTrek.sln --configfile src/NuGet.config

        