name: TechTrek Build

on:
    push:
        branches: [ main ]


jobs:
    build:

        runs-on: ubuntu-latest

        services:
            sql-server:
                image: mcr.microsoft.com/mssql/server:2019-latest
                env:
                    SA_PASSWORD: "Password123"
                    ACCEPT_EULA: "Y"
                ports:
                    - 14331:1433
                #options: --health-cmd "SELECT 1" --health-interval 10s --health-timeout 5s --health-retries 5

        steps:

        - name: Checkout source
          uses: actions/checkout@v4

        - name: Print workspace path
          run: | 
              echo "Workspace directory: $GITHUB_WORKSPACE"

        - name: List files in /src directory
          run: |
            echo "Listing files and directories in the workspace /src directory:"
            ls -alh "${GITHUB_WORKSPACE}/src"
  
        - name: Setup .NET 9.0
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '9.0.x'

        - name: Install required Aspire workloads
          run: |
            dotnet workload update --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" --skip-sign-check
            dotnet workload install aspire --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" --skip-sign-check 
            # Add more as needed

        - name: Restore dependencies using nuget.config
          run: dotnet restore src/Nabs.TechTrek.sln --configfile ./src/nuget.config

        - name: Build Solution
          run: dotnet build src/Nabs.TechTrek.sln --configuration Release --no-restore

        - name: Reset the Test Scenario Databases
          shell: pwsh
          run: ./src/Persistence/Nabs.TechTrek.PersistenceCli/ResetDatabases.ps1
          
        - name: Run Solution Tests with code coverage
          run: dotnet test src/Nabs.TechTrek.sln \
            --configuration Release \
            --no-restore \
            --no-build \
            --logger "trx;LogFileName=TestResults/testresults.trx" \
            --logger "console;verbosity=detailed" \
            --settings src/coverlet.runsettings

        - name: Install ReportGenerator
          run: dotnet tool install --global dotnet-reportgenerator-globaltool

        - name: Upload Test Results
          uses: actions/upload-artifact@v4
          with:
            name: TestResults
            path: TestResults/test_results.trx

        - name: Publish Test Annotations
          uses: dorny/test-reporter@v1
          with:
            name: Unit Tests
            path: TestResults/test_results.trx
            reporter: dotnet-trx
          
        - name: Generate Code Coverage report
          env:
            PATH: ${{ env.PATH }}:$HOME/.dotnet/tools
          run: reportgenerator -reports:**/TestResults/*/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html,MarkdownSummaryGithub

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./coveragereport
            destination_dir: coverage
